// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSlides() {
  return window['go']['main']['App']['GetSlides']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadPresentation(arg1) {
  return window['go']['main']['App']['LoadPresentation'](arg1);
}

export function SendMessageToAI(arg1) {
  return window['go']['main']['App']['SendMessageToAI'](arg1);
}
