// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSlideExists(arg1) {
  return window['go']['main']['App']['CheckSlideExists'](arg1);
}

export function ClearImageCache() {
  return window['go']['main']['App']['ClearImageCache']();
}

export function GetSlideImageAsBase64(arg1) {
  return window['go']['main']['App']['GetSlideImageAsBase64'](arg1);
}

export function GetSlideImagePath(arg1) {
  return window['go']['main']['App']['GetSlideImagePath'](arg1);
}

export function GetSlideImageQuiet(arg1) {
  return window['go']['main']['App']['GetSlideImageQuiet'](arg1);
}

export function GetSlides() {
  return window['go']['main']['App']['GetSlides']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadPresentation(arg1) {
  return window['go']['main']['App']['LoadPresentation'](arg1);
}

export function OpenPresentationDialog() {
  return window['go']['main']['App']['OpenPresentationDialog']();
}

export function SendMessageToAI(arg1) {
  return window['go']['main']['App']['SendMessageToAI'](arg1);
}
