// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSlideExists(arg1:string):Promise<boolean>;

export function ClearImageCache():Promise<void>;

export function GetSlideImageAsBase64(arg1:string):Promise<string>;

export function GetSlideImagePath(arg1:string):Promise<string>;

export function GetSlideImageQuiet(arg1:string):Promise<string>;

export function GetSlides():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function LoadPresentation(arg1:string):Promise<Array<string>>;

export function OpenPresentationDialog():Promise<Array<string>>;

export function SendMessageToAI(arg1:string):Promise<string>;
